config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "static_pages#home"
  get "home" => "static_pages#home"
  get "help" => "static_pages#help"
  get "about"   => "static_pages#about"
  get "contact" => "static_pages#contact"

  namespace :admin do
    resources :categories
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new
    if user.admin?
      can :manage, :all
    elsif user.member?
      can :read, :all
      can [:edit, :update], User, id: user.id
    else
      can :read, :all
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  has_many :cart_details
end

app/models/cart_detail.rb
class CartDetail < ApplicationRecord
  belongs_to :cart
  belongs_to :drink
end

app/models/category.rb
class Category < ApplicationRecord
  include Kaminari::ActiveRecordModelExtension
  has_many :drinks

  validates :title, presence: true, length: {maximum: 50},
    uniqueness: {case_sensitive: false}
end

app/models/drink.rb
class Drink < ApplicationRecord
  has_many :favorites
  has_many :reviews
  belongs_to :category
  has_many :cart_details

  validates :name, presence: true, length: {maximum: 50}
  validates :description, presence: true, length: {maximum: 500}
end

app/models/favorite_list.rb
class FavoriteList < ApplicationRecord
  belongs_to :user
  belongs_to :drink
end

app/models/request.rb
class Request < ApplicationRecord
  belongs_to :user

  enum status: [:not_accept, :pending, :accepted, :rejected]
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :drink
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :name, presence: true, length: {maximum: 20},
    uniqueness: {case_sensitive: false}

  has_many :carts
  has_many :requests
  has_many :favorites
  has_many :reviews

  enum role: [:admin, :member, :guest]
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
  load_and_authorize_resource

  def index
    @categories = Kaminari.paginate_array(Category.all.order(created_at: :desc))
      .page(params[:page]).per Settings.per_page
  end

  def new
    @category = Category.new
  end

  def show
  end

  def edit
  end

  def update
    if @category.update_attributes category_params
      flash[:success] = "Update success"
      redirect_to admin_categories_path
    else
      render :edit
    end
  end

  def create
    @category = Category.new category_params
    if @category.save
      flash[:success] = "Create success"
      redirect_to admin_categories_path
    else
      render :new
    end
  end

  private
  def category_params
    params.require(:category).permit :title
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    return request.env['omniauth.origin'] || session[:user_return_to] || root_path
  end


  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit :sign_up do |user|
      user.permit :name, :email, :password, :password_confirmation,
        :remember_me, :avatar
    end
    devise_parameter_sanitizer.permit :account_update do |user|
      user.permit :name, :email, :password, :password_confirmation,
        :current_password, :avatar
    end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end

  def help
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/categories/edit.html.erb
<% provide :title, "edit category" %>
<h1><%= "Edit category" %></h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for [:admin, @category] do |f| %>
      <%= render "shared/error_message" , object: f.object %>
      <%= f.label :title %>
      <%= f.text_field :title, class: "form-control" %>

      <%= f.submit "Save", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/admin/categories/index.html.erb
<% provide :title, "Categories" %>
<h1><%= "All categories" %></h1>
<table class="table table-striped">
  <thead>
    <th class="number"><%= "Number" %></th>
    <th class="title"><%= "Title" %></th>
    <th class="number drinks"><%= "Number of drinks"%></th>
    <th class="action"><%= "Action" %></th>
  </thead>
  <% @categories.each_with_index do |category, index| %>
  <tbody>
    <tr>
      <td class="category-id"><%= index+1 %></td>
      <td><%= link_to category.name, admin_categories_path %></td>
      <td><%= category.drinks.count %></td>
      <td>
        <%= link_to new_admin_book_path(id: category.id),
          data: {toggle: "tooltip", placement: "top"},
          title: "Add category" do %>
          <span class= "glyphicon glyphicon-plus" ></span>
        <% end %>
        <%= link_to edit_admin_category_path(category),
          data: {toggle: "tooltip", placement: "top"},
          title: "Edit Category" do %>
          <span class= "glyphicon glyphicon-pencil" ></span>
        <% end %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>
<%= paginate @categories %>
<div>
  <%= link_to "Add category", new_admin_category_path,
    class: "btn btn-primary" %>
</div>

app/views/admin/categories/new.html.erb
<% provide :title, "add category" %>
<h1><%= "Add category" %></h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for [:admin, @category] do |f| %>
    <%= render "shared/error_message" , object: f.object %>
      <%= f.label :title %>
      <%= f.text_field :title, class: "form-control" %><br>

      <%= f.submit "Add", class: "btn btn-primary form-control" %>
    <% end %>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <a>Drinks Mart System</a>
    by <a href="https://www.facebook.com/trongnghia.nguyenthi">Trong Nghia</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   '#' %></li>
      <li><%= link_to "Contact", '#' %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Drinks Mart", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Help", help_path %></li>
        <% if user_signed_in? %>
          <li><%= link_to "Users", users_path %></li>
          <% if current_user.admin? %>
            <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <%= t "views.header.books.book" %><b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li>
                <%= link_to t("views.header.books.list_books"), books_path %>
              </li>
              <li>
                <%= link_to t("views.header.books.request"),
                  book_requests_path %>
              </li>
            </ul>
          </li>
          <% else %>

          <% end %>
        <% else %>
          <li><%= link_to "Log in", new_user_session_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= "Drinks Mart" %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/static_pages/about.html.erb
<% provide :title, "About us" %>
<h1><%= "Nguyen Thi Trong Nghia" %></h1>

app/views/static_pages/contact.html.erb
<% provide :title, "Contact" %>
<h1><%= "Contact us: 01658 125 527" %></h1>

app/views/static_pages/help.html.erb
<% provide :title, "Contact" %>
<h1><%= "Contact us: 01658 125 527" %></h1>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
 <div class="home">
    <% if user_signed_in? %>
      <h2><%= "Drink Mart System" %></h2>
    <% end %>
  </div>
</div>

<%= link_to image_tag("rails.png", alt: "Rails logo"),
            'http://rubyonrails.org/' %>